# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "badmama"
  config.vm.box = "quantal64-vanilla"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/165709740/boxes/quantal64-vanilla.box"
  config.vm.network :private_network, ip: "33.33.33.10"
  config.berkshelf.enabled = true
  
  config.vm.provision :shell do |sh|
    sh.inline = <<-EOF
      sudo apt-get update
      sudo apt-get install ruby1.9.3 --yes
      sudo gem install chef --version 11.4.4 --no-ri --no-rdoc
    EOF
  end

  config.vm.provision :chef_solo do |chef|
    chef.json = {
      :mysql => {
        :bind_address => '0.0.0.0',
        :allow_remote_root => true,
        :server_root_password => '',
        :server_debian_password => '',
        :server_repl_password => ''
      }
    }

    chef.run_list = [
      "recipe[apt]",
      "recipe[build-essential]",
      "recipe[mysql::server]"
    ]
  end

  config.vm.provision :shell do |sh|
    sh.inline = <<-EOF
      mysql -e 'create database if not exists badmama;'
    EOF
  end
end
